### ISSUE TITLE
Add a link for each child button ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [ifndefdeadmau5/react-floating-button-menu#1]
Yopp, 
I did not find the props while allow me to add a redirection link for child button ? 
Thx

**Comment by ifndefdeadmau5** [comment]
You can pass `onClick`  event props to each button so that implement your custom behaviour

**Comment by be-next-hotdog** [comment]
Yep, I've tried this way but it will triggers immediately ChildButton onClick event while we click the MainButton and ChildButton is not a subnode of MainButton ... Have you showcase online ? 

Thx a lot.

**Comment by be-next-hotdog** [comment]
I've tried many times, I really had no idea why this triggered automatically the childbutton onclick event while clicking mainbutton.

**Comment by be-next-hotdog** [comment]
I found out, the ChildButton covers always MainButton as you defined opacity: 0 while the menu is not active. It'd better assign `z-index` to each component I think.
