### ISSUE TITLE
Tooltip in buttons

### ISSUE THREAD

**Issue by Gustavoaz** [ifndefdeadmau5/react-floating-button-menu#14]
Tooltip in "MainButton" and "ChildButton"

**Comment by Karl992** [comment]
You can easily add a tooltip in each button by wrapping the icon inside a Tooltip Component from Material-UI:
`
<ChildButton 
icon={<Tooltip title="Your tooltip" placement="left"><YourIcon/></Tooltip>}
/>
`

**Comment by ifndefdeadmau5** [comment]
@Karl992 Thank you for such a nice workaround, gotta add demo about that :)
