### ISSUE TITLE
Update `yargs`  dependency - npm audit throws vulnerability

### ISSUE THREAD

**Issue by appidea** [ifndefdeadmau5/react-floating-button-menu#27]
NPM detects a vulnerability on the following path:
`react-floating-button-menu > yargs > os-locale > mem `
(possible DOS in `mem` package).

However it's still autofixing using `npm audit`, would be nice to update the dependencies.

**Comment by ifndefdeadmau5** [comment]
Will fix this, thanks!

**Comment by ifndefdeadmau5** [comment]
published v2.0.7 :)
