### ISSUE TITLE
npm version 2.0.7 has no code in it

### ISSUE THREAD

**Issue by aequasi** [ifndefdeadmau5/react-floating-button-menu#31]

**Comment by ifndefdeadmau5** [comment]
@aequasi Oh shit, must've something bad happened while dependencies update :(
Sorry!

**Comment by ifndefdeadmau5** [comment]
@aequasi I have no idea what exactly was wrong in the npm publish process, but when I just republished it, it now has build output code in the package on 2.0.8 🤷‍♂ if you still have issues about this, feel free to re-open it :)
