### ISSUE TITLE
Add license information to package.json

### ISSUE THREAD

**Issue by dalevy** [ifndefdeadmau5/react-floating-button-menu#34]
Hello and thank you for this wonderful library. On your next publish could you please add   "license": "MIT", to your package.json so that npm will show the project has the MIT license? It is visible on github but not on npm and that lack of visibility could deter some corporate users from  using the library.

**Comment by ifndefdeadmau5** [comment]
@dalevy Thank you for those kind words :) I'll definitely add license info on next release.
