### ISSUE TITLE
direction top and bottom don't work

### ISSUE THREAD

**Issue by MohammedAijaaz** [ifndefdeadmau5/react-floating-button-menu#4]
For direction attr, top and bottom both make the child buttons open from top to bottom and not the other way, also it will be awesome if you add a good guide on the list of attributes and values for them.

**Comment by ifndefdeadmau5** [comment]
Hello @MohammedAijaaz ,
Please see the issue that I recently submitted, thanks.

**Comment by ifndefdeadmau5** [comment]
Will adding `docs` section soon
