### ISSUE TITLE
Labels for each ChildButton

### ISSUE THREAD

**Issue by smurancsik** [ifndefdeadmau5/react-floating-button-menu#49]
Is there a way to add optional "labels" next to the buttons, similarly like in this screenshot?

![image](https://user-images.githubusercontent.com/10431363/103346197-9e373c00-4a93-11eb-9f78-b0c4dd6fae22.png)

Thank you!

**Comment by ifndefdeadmau5** [comment]
I believe you can make use of Material UI's [Tooltip](https://material-ui.com/components/tooltips/#tooltip) component, direct support from this lib isn't available at the moment

**Comment by smurancsik** [comment]
If the Material UI can be used, this component can be replaced with [Speed Dial](https://material-ui.com/components/speed-dial/).

**Comment by smurancsik** [comment]
If the Material UI can be used, this component can be replaced with [Speed Dial](https://material-ui.com/components/speed-dial/).
