### ISSUE TITLE
onClick

### ISSUE THREAD

**Issue by genericjohndoe** [ifndefdeadmau5/react-floating-button-menu#5]
The onClick functionality doesn't seem to be working for me. Did I it set up correct?

<ChildButton
            iconButton={envelopeIcon}
            iconColor="white"
            order={1}
            backgroundColor="#5a7f93"
            buttonSize="56"
            onClick={this.sendPdf()}/>

**Comment by ifndefdeadmau5** [comment]
Hello @genericjohndoe,
Please check out the issue that I recently submitted, thanks.
