### ISSUE TITLE
on Edge, icons are behind background

### ISSUE THREAD

**Issue by AmitTurner** [ifndefdeadmau5/react-floating-button-menu#8]
Im trying to make the button work, but on edge, the "background" is blocking the actual icons or text on the button.
Ive tried the default settings as well from your docs.
this is how it looks side to side with background and without:
![ApplicationFrameHost_2019-03-13_13-51-03](https://user-images.githubusercontent.com/19940028/54276968-43b7ad80-4597-11e9-8f1e-27987a4196e2.png)

any Advices?

**Comment by ifndefdeadmau5** [comment]
Background shouldn't block any children by default :/
Could you provide reproduction example? https://codesandbox.io/ would be a good start :)

**Comment by melvin1992** [comment]
@ifndefdeadmau5 Simply opening the demo page in Edge you can see that the icon is blocked by the background.

**Comment by melvin1992** [comment]
@ifndefdeadmau5 updating the CSS position attribute in `IconWrapper` from absolute to static or removing that attribute fix the issue.

**Comment by ifndefdeadmau5** [comment]
@melvin1992 Oh I didn't realize that the author meant the browser's name 😭, I'll fix this soon

**Comment by ifndefdeadmau5** [comment]
Fixed on v2.0.2
